[package]
name = "rosalind"
version = "0.1.0"
authors = ["Alan Kavishe <afksavish@gmail.com>"]
edition = "2018"

[dependencies]
modular = "~1"

[dependencies.clap]
version = "~2.31.0"
features = ["yaml"]