[package]
name = "rosalind"
version = "0.1.0"
authors = ["Alan Kavishe <afksavish@gmail.com>"]

[dependencies]
gen_str = { path = "gen_str" }
fib = { path = "fib" }
perm = { path = "perm" }
gene = { path = "gene" }

[workspace]